FROM docker.io/n8nio/n8n:2.36.9

ENV N8N_PORT=10000 \
    N8N_LISTEN_ADDRESS=0.0.0.0 \
    N8N_DIAGNOSTICS_ENABLED=false \
    N8N_PERSONALIZATION_ENABLED=false \
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true \
    N8N_RUNNERS_ENABLED=false \
    GENERIC_TIMEZONE=America/Sao_Paulo \
    TZ=America/Sao_Paulo

EXPOSE 10000
